// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reiklander.Infrastructure.Persistence;

#nullable disable

namespace Reiklander.Infrastructure.Migrations
{
    [DbContext(typeof(EventStoreDbContext))]
    [Migration("20260428134646_RenameToCharacteristic")]
    partial class RenameToCharacteristic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reiklander.Infrastructure.Persistence.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacterReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceSpent")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacterReadModel", b =>
                {
                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Agility", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "BallisticSkill", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Dexterity", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Fellowship", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Initiative", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Intelligence", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Strength", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Toughness", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "WeaponSkill", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.OwnsOne("Reiklander.Infrastructure.Queries.Characters.ReadModels.CharacteristicReadModel", "Willpower", b1 =>
                        {
                            b1.Property<Guid>("CharacterReadModelId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Advances")
                                .HasColumnType("integer");

                            b1.Property<int>("Bonus")
                                .HasColumnType("integer");

                            b1.Property<int>("CostToAdvance")
                                .HasColumnType("integer");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("CharacterReadModelId");

                            b1.ToTable("Characters");

                            b1.WithOwner()
                                .HasForeignKey("CharacterReadModelId");
                        });

                    b.Navigation("Agility")
                        .IsRequired();

                    b.Navigation("BallisticSkill")
                        .IsRequired();

                    b.Navigation("Dexterity")
                        .IsRequired();

                    b.Navigation("Fellowship")
                        .IsRequired();

                    b.Navigation("Initiative")
                        .IsRequired();

                    b.Navigation("Intelligence")
                        .IsRequired();

                    b.Navigation("Strength")
                        .IsRequired();

                    b.Navigation("Toughness")
                        .IsRequired();

                    b.Navigation("WeaponSkill")
                        .IsRequired();

                    b.Navigation("Willpower")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
